name: Build and Release for Raspberry Pi Zero 2W

on:
    push:
      branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build using Docker
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker build -f Dockerfile.rpi-zero -t motor-controller-builder .
          docker create -ti --name builder motor-controller-builder bash
          docker cp builder:/app/motor_controller .
          docker rm -f builder

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./motor_controller
          asset_name: motor_controller-rpi-zero-2w
          asset_content_type: application/octet-stream