name: Build for RPi Zero 2W

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Docker image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build \
            --platform linux/arm/v6 \
            -f Dockerfile.rpi-zero \
            -t motor-builder \
            --output type=local,dest=./artifact \
            .

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/app/build/DecentralizedSynchronization
          tag_name: rpi-zero-${{ github.sha }}
          name: RPi Zero Build
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}