name: Build and Release for Raspberry Pi Zero 2W

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CACHE_KEY: ${{ runner.os }}-rpi-zero-build-${{ hashFiles('**/CMakeLists.txt', '**/*.cpp', '**/*.h') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/cache/wiringpi
            ~/cache/oscpack
            ~/cache/build
          key: ${{ env.CACHE_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with cache
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.rpi-zero
          platforms: linux/arm/v6
          tags: rpi-zero-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=./build

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/motor_controller
          asset_name: motor_controller-rpi-zero-2w
          asset_content_type: application/octet-stream